### ISSUE TITLE
Derived Identities - DBValidationException 

### ISSUE THREAD

**Issue by jGauravGupta** [jeddict/JPAModeler#164]
Message : Exception Description: 

StackTrace : 
Local Exception Stack: 
Exception [EclipseLink-7321] (Eclipse Persistence Services - 2.6.2.v20151217-774c696): org.netbeans.db.modeler.exception.DBValidationException
Exception Description: 
	at org.netbeans.jpa.modeler.db.accessor.OneToOneSpecAccessor.process(OneToOneSpecAccessor.java:78)
	at org.eclipse.persistence.internal.jpa.metadata.accessors.classes.ClassAccessor.processDerivedId(ClassAccessor.java:1619)
	at org.eclipse.persistence.internal.jpa.metadata.accessors.classes.EntityAccessor.processDerivedId(EntityAccessor.java:993)
	at org.eclipse.persistence.internal.jpa.metadata.MetadataProject.processAccessorsWithDerivedIDs(MetadataProject.java:1539)
	at org.eclipse.persistence.internal.jpa.metadata.MetadataProject.processStage3(MetadataProject.java:1836)
	at org.eclipse.persistence.internal.jpa.metadata.MetadataProcessor.processORMMetadata(MetadataProcessor.java:577)
	at org.netbeans.db.modeler.persistence.internal.jpa.deployment.JPAMPersistenceUnitProcessor.processORMetadata(JPAMPersistenceUnitProcessor.java:49)
	at org.netbeans.db.modeler.specification.model.util.DBModelerUtil.createDBMapping(DBModelerUtil.java:248)
	at org.netbeans.db.modeler.specification.model.util.DBModelerUtil.loadModelerFileInternal(DBModelerUtil.java:189)
	at org.netbeans.db.modeler.specification.model.util.DBModelerUtil.loadModelerFile(DBModelerUtil.java:173)
	at org.netbeans.modeler.core.NBModelerUtil.loadModelerFile(NBModelerUtil.java:62)
	at org.netbeans.modeler.specification.model.file.action.ModelerFileActionListener.openModelerFile(ModelerFileActionListener.java:147)
	at org.netbeans.db.modeler.specification.model.file.action.DBViewerActionListener.init(DBViewerActionListener.java:59)
	at org.netbeans.jpa.modeler.specification.model.util.DBUtil.openDBViewer(DBUtil.java:86)
	at org.netbeans.jpa.modeler.specification.model.event.JPAEventListener$2.actionPerformed(JPAEventListener.java:53)
	at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1663)
	at javax.swing.JComponent.processKeyBinding(JComponent.java:2882)
	at javax.swing.JComponent.processKeyBindings(JComponent.java:2929)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2845)
	at java.awt.Component.processEvent(Component.java:6312)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:806)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771)
	at java.awt.Component.dispatchEventImpl(Component.java:4762)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

ModelerFile : 
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<jpa:entity-mappings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:java="http://jcp.org/en/jsr/detail?id=270" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:jpa="http://java.sun.com/xml/ns/persistence/orm" pkg="com.mycompany.mavenproject9" v="3.6" rws="_14895165060692" Pws="_14895165060692" cws="_14895165060692" sm="false" xs="false" id="_14895165060681" xsi:schemaLocation="http://java.sun.com/xml/ns/persistence/orm orm_2_1.xsd">
    <jpa:entity xre="false" compositePrimaryKeyType="D" compositePrimaryKeyClass="PersonPK" abs="false" class="Employee" v="true" m="false" rootElement="_14895165060681" id="_1489516542558">
        <jpa:ts e="true"/>
        <jpa:hc e="true"/>
        <jpa:eq e="true"/>
        <jpa:ath>jGauravGupta</jpa:ath>
        <jpa:attributes>
            <jpa:one-to-one orp="false" optional="true" primaryKey="false" connected-entity-id="_1489597262352" connected-attribute-id="_14895972717275" v="true" name="dependent" id="_14895972717356">
                <jpa:bv/>
            </jpa:one-to-one>
            <jpa:id attribute-type="Long" v="true" name="fname" id="_14895165427623">
                <jpa:bv/>
                <jpa:generated-value strategy="AUTO"/>
            </jpa:id>
            <jpa:id attribute-type="Long" v="true" name="lname" id="_148959791166674">
                <jpa:bv/>
                <jpa:generated-value/>
            </jpa:id>
        </jpa:attributes>
        <jpa:nq e="false" name="Employee.findAll">
            <jpa:query>Select e from Employee e</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Employee.findByFname">
            <jpa:query>Select p from Employee p where p.fname=:fname</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Employee.findByLname">
            <jpa:query>Select p from Employee p where p.lname=:lname</jpa:query>
        </jpa:nq>
        <jpa:el/>
    </jpa:entity>
    <jpa:entity xre="false" compositePrimaryKeyType="EMBEDDEDID" compositePrimaryKeyClass="Entity_1PK" abs="false" class="Dependent" v="true" m="false" rootElement="_14895165060681" id="_1489597262352">
        <jpa:ts e="true"/>
        <jpa:hc e="true"/>
        <jpa:eq e="true"/>
        <jpa:ath>jGauravGupta</jpa:ath>
        <jpa:attributes>
            <jpa:one-to-one own="true" orp="false" optional="true" primaryKey="true" maps-id="emp" connected-entity-id="_1489516542558" connected-attribute-id="_14895972717356" v="true" name="emp" id="_14895972717275">
                <jpa:bv/>
                <jpa:join-column name="PERSON_ID1" rc="ID1" unique="false" nullable="true" insertable="true" updatable="true"/>
                <jpa:join-column name="PERSON_ID" rc="ID" unique="false" nullable="true" insertable="true" updatable="true"/>
            </jpa:one-to-one>
            <jpa:id attribute-type="Long" v="true" name="name" id="_148959786633850">
                <jpa:bv/>
                <jpa:generated-value strategy="AUTO"/>
            </jpa:id>
            <jpa:embedded-id v="true" name="id" id="_1489597982762105">
                <jpa:bv/>
            </jpa:embedded-id>
        </jpa:attributes>
        <jpa:nq e="false" name="Dependent.findAll">
            <jpa:query>Select e from Dependent e</jpa:query>
        </jpa:nq>
        <jpa:el/>
    </jpa:entity>
    <jpa:snp loc="BEFORE_PACKAGE" e="true">/**
 * This file was generated by the JPA Modeler
 */</jpa:snp>
    <jpa:c/>
    <jpa:wsl>
        <jpa:ws n="Main" id="_14895165060692">
            <i ref="_1489597262352" x="387" y="276"/>
            <i ref="_1489516542558" x="83" y="219"/>
        </jpa:ws>
    </jpa:wsl>
</jpa:entity-mappings>
```

**Comment by jGauravGupta** [comment]
REF : http://localhost:8383/jeddict/page.html?l=tutorial/DerivedIdentities
Testing required for above tutorial.

**Comment by jGauravGupta** [comment]
Duplicate Issue Ref : #141
